"""Freeze the completed P15 proof and foundation/coverage review as exact bytes."""
from pathlib import Path
import hashlib
import json
import zipfile

ROOT = Path(__file__).resolve().parent
DEST = ROOT.parent / "P15_FOUNDATION_FIRST_20260921_v1.zip"
PARENT_FILES = (
    "README.md", "CLOSURE_FRONTIER.md", "ANALYTIC_FRONTIER_REVIEW.md",
    "P15_FOUNDATION_REVIEW.md", "SOURCE_COVERAGE_REVIEW.md",
    "LIVE_P15_SOURCE_CHECK.json", "claim_receipt.json",
    "VALIDATION.json", "build_delivery.py", "delivery_claim_receipt.json",
    "SOURCE_COVERAGE_REVIEW.json", "SOURCE_COVERAGE_LIVE_METADATA.json",
    "SOURCE_COVERAGE_NEW_MATH.json", "SOURCE_COVERAGE_EXISTING_MATH_SUMMARIES.json",
)


def sha(data):
    return hashlib.sha256(data).hexdigest()


def main():
    if DEST.exists():
        raise RuntimeError("Immutable delivery already exists; create a numbered successor")
    members = {}
    for name in PARENT_FILES:
        members[name] = (ROOT / name).read_bytes()
    for path in sorted(p for subtree in ("p15_hypergraph", "incoming", "validation_logs")
                       for p in (ROOT / subtree).rglob("*")):
        if path.is_symlink():
            raise RuntimeError("Source packet contains a symlink")
        if path.is_file():
            if "__pycache__" in path.parts or path.suffix == ".pyc":
                raise RuntimeError("Source packet contains generated bytecode")
            members[path.relative_to(ROOT).as_posix()] = path.read_bytes()
    if "p15_hypergraph/PROOF.md" not in members:
        raise RuntimeError("Missing proof")
    sources = json.loads(members["p15_hypergraph/SOURCES.json"])
    for source in sources["sources"]:
        body = members["p15_hypergraph/" + source["copy_path"]]
        if len(body) != source["bytes"] or sha(body) != source["sha256"]:
            raise RuntimeError("Foundational source identity mismatch")
    validation = json.loads(members["VALIDATION.json"])
    if validation["passed"] is not True:
        raise RuntimeError("Companion validation did not pass")
    for name, expected in validation["candidate_files"].items():
        data = members["p15_hypergraph/" + name]
        if {"bytes": len(data), "sha256": sha(data)} != expected:
            raise RuntimeError("Candidate changed after root validation")
    manifest = {
        "schema": "P15_FOUNDATION_FIRST_DELIVERY_V1",
        "claim": "CLAIM-P15-FINITE-RANK-20260921-ROOT01",
        "source_proofs_are_technical_review_candidates": True,
        "organizational_independence_credit": 0,
        "original_prize_closed": False,
        "q0_closed": False,
        "canonical_status_changed": False,
        "members": [{"path": n, "bytes": len(b), "sha256": sha(b)}
                    for n, b in sorted(members.items())],
    }
    members["DELIVERY_MANIFEST.json"] = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    with zipfile.ZipFile(DEST, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for name, data in sorted(members.items()):
            info = zipfile.ZipInfo(name, (2026, 9, 21, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, data)
    with zipfile.ZipFile(DEST) as archive:
        if set(archive.namelist()) != set(members):
            raise RuntimeError("Archive membership mismatch")
        for name, data in members.items():
            if archive.read(name) != data:
                raise RuntimeError("Archive byte mismatch")
    for name, data in members.items():
        if name == "DELIVERY_MANIFEST.json":
            continue
        if (ROOT / name).read_bytes() != data:
            raise RuntimeError("Input changed during freezing")
    receipt = {"path": str(DEST), "bytes": DEST.stat().st_size,
               "sha256": sha(DEST.read_bytes()), "members": len(members),
               "proof_sha256": sha(members["p15_hypergraph/PROOF.md"]),
               "archive_members_roundtrip_equal": True}
    (ROOT / "DELIVERY_RECEIPT.json").write_text(json.dumps(receipt, indent=2) + "\n")
    print(json.dumps(receipt, sort_keys=True))


if __name__ == "__main__":
    main()
