#!/usr/bin/env python3
"""Which register tabs anything in this repository actually reads.

``tools/registers_check.py`` walks ``registers/json/*.json`` generically and
checks every tab's structure without naming any of them, so a tab can be
exported, imported and structurally checked while **nothing in the repository
ever reads its cells**.  This checker makes that difference visible and keeps
it honest: ``registers/CONSUMERS.json`` records, per tab, the files that name
it, and this tool recomputes the scan and refuses any drift.

Three classes, all *derived* from the scan and never typed by hand:

``MACHINE``      at least one non-generic file under a code root, or a
                 non-export JSON data file under ``registers/``, names the tab
                 as ``<tab>.json`` or as a quoted token ``"<tab>"`` /
                 ``'<tab>'``.  That file reads or pins that tab's content.
``PROSE_ONLY``   no such file, but at least one Markdown file names it as
                 ``<tab>.json`` or in backticks.  The tab is quoted, not read.
``UNREAD``       neither.  The tab is carried, exported and structurally
                 checked, and nothing else in the repository names it.

Files that name at least ``generic_threshold`` of the tabs are **generic
machinery** (the importer, its export diff, its test, the register README's own
tab list).  They touch every tab by construction, so counting them as
per-tab consumers would make every tab look consumed.  They are recorded
separately and excluded from per-tab attribution.

What this does NOT establish: nothing here reads, checks or grades any cell.
A tab with many consumers is not more correct than a tab with none, an
``UNREAD`` tab is not defective — it is simply not used here — and no class in
this map is a status, a promotion, a review or a licensing predicate.  The map
measures this repository's coverage of the export, not the export's coverage
of the Drive, and not the truth of anything either one says.

Run:  python3 tools/consumers_check.py [--root DIR] [--map PATH] [--json-dir DIR]
      python3 tools/consumers_check.py --write     # regenerate the map
Every path is resolved when ``main()`` runs, never at import time.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAP_REL = os.path.join("registers", "CONSUMERS.json")
JSON_REL = os.path.join("registers", "json")
# Machinery *about* consumption, excluded from the corpus it scans: the map
# itself, this checker and its controls.  They name tabs only to describe or
# to test the rule -- this file's own docstring quotes 'definitions' and
# 'relations' as examples -- and counting that as reading a tab would invent
# exactly the false consumers the prose rule exists to prevent.
MAP_MACHINERY = (
    os.path.join("tools", "consumers_check.py"),
    os.path.join("tests", "test_consumers.py"),
    os.path.join("docs", "REGISTER_CONSUMERS.md"),
)

# Exported data: regenerated by tools/registers_import.py, never a consumer.
EXPORT_DIRS = (
    os.path.join("registers", "source"),
    os.path.join("registers", "json"),
    os.path.join("registers", "csv"),
)
# Roots whose files can read a tab's cells.
CODE_ROOTS = ("tools", "tests", "engine", "research", "claims")
# Non-export JSON under registers/ (KNOWN_FINDINGS, the collision proposals):
# these pin named tabs and rows, so they read tabs by name.
DATA_ROOTS = ("registers",)
# Everything whose Markdown may quote a tab.
PROSE_ROOTS = ("tools", "tests", "engine", "research", "claims", "docs",
               "governance", "quarantine", "recovery", "reviews", "packages",
               "legacy", "sandbox", "drive", "registers", "README.md", "CLAUDE.md")
MAX_BYTES = 3_000_000
SCHEMA = "q0.register-consumers/v1"


def tabs_of(json_dir: str) -> list[str]:
    return sorted(f[:-5] for f in os.listdir(json_dir) if f.endswith(".json"))


def _files(root: str, roots, exts=None) -> list[str]:
    out: list[str] = []
    for rel in roots:
        base = os.path.join(root, rel)
        if os.path.isfile(base):
            out.append(rel)
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d != "__pycache__"]
            for name in filenames:
                path = os.path.join(dirpath, name)
                rel_path = os.path.relpath(path, root)
                if rel_path.startswith(EXPORT_DIRS):
                    continue
                if exts and not name.endswith(exts):
                    continue
                try:
                    if os.path.getsize(path) > MAX_BYTES:
                        continue
                except OSError:
                    continue
                out.append(rel_path)
    return sorted(set(out))


def _read(root: str, rel: str) -> str:
    try:
        with open(os.path.join(root, rel), encoding="utf-8", errors="replace") as handle:
            return handle.read()
    except OSError:
        return ""


def machine_names(text: str, tabs) -> set[str]:
    """Tabs this file names in a form that reads or pins the tab's content."""
    return {t for t in tabs
            if (t + ".json") in text or ('"' + t + '"') in text or ("'" + t + "'") in text}


def prose_names(text: str, tabs) -> set[str]:
    """Tabs this Markdown names as a path or a backticked token.

    A bare word is not enough: 'definitions' and 'relations' are ordinary
    English, and counting them would invent consumers that do not exist.
    """
    return {t for t in tabs if (t + ".json") in text or ("`" + t + "`") in text}


def scan(root: str, json_dir: str, generic_threshold: int, self_rel: str = "") -> dict:
    """Scan the repository.  ``self_rel`` is the map's own path; it and
    ``MAP_MACHINERY`` are excluded from the corpus, because a record of which
    files read a tab is not itself a reader."""
    tabs = tabs_of(json_dir)
    skip = set(MAP_MACHINERY)
    if self_rel:
        skip.add(os.path.normpath(self_rel))
    code = [(p, _read(root, p)) for p in _files(root, CODE_ROOTS) if p not in skip]
    code += [(p, _read(root, p)) for p in _files(root, DATA_ROOTS, exts=(".json",)) if p not in skip]
    prose = [(p, _read(root, p)) for p in _files(root, PROSE_ROOTS, exts=(".md",)) if p not in skip]
    code = sorted(set(code))
    named_code = {p: machine_names(s, tabs) for p, s in code}
    named_prose = {p: prose_names(s, tabs) for p, s in prose}
    generic = sorted({p for p, n in named_code.items() if len(n) >= generic_threshold}
                     | {p for p, n in named_prose.items() if len(n) >= generic_threshold})
    gset = set(generic)
    entries = {}
    for tab in tabs:
        machine = sorted(p for p, n in named_code.items() if p not in gset and tab in n)
        quoted = sorted(p for p, n in named_prose.items() if p not in gset and tab in n)
        entries[tab] = {
            "class": "MACHINE" if machine else ("PROSE_ONLY" if quoted else "UNREAD"),
            "machine": machine,
            "prose": quoted,
        }
    counts = {"tabs": len(tabs), "generic_files": len(generic)}
    for cls in ("MACHINE", "PROSE_ONLY", "UNREAD"):
        counts[cls] = sum(1 for e in entries.values() if e["class"] == cls)
    return {"generic_files": generic, "tabs": entries, "counts": counts}


def load_map(path: str) -> dict:
    with open(path, encoding="utf-8") as handle:
        doc = json.load(handle)
    if not isinstance(doc, dict) or doc.get("schema") != SCHEMA:
        raise ValueError(f"{path}: not a {SCHEMA} document")
    for key in ("generic_threshold", "generic_files", "tabs", "counts",
                "map_machinery", "does_not_establish"):
        if key not in doc:
            raise ValueError(f"{path}: missing {key!r}")
    if not isinstance(doc["generic_threshold"], int) or not 2 <= doc["generic_threshold"]:
        raise ValueError(f"{path}: generic_threshold must be an integer of at least 2")
    if not isinstance(doc["tabs"], dict) or not doc["tabs"]:
        raise ValueError(f"{path}: tabs must be a non-empty mapping")
    return doc


def check(root: str, map_path: str, json_dir: str) -> list[str]:
    problems: list[str] = []
    doc = load_map(map_path)
    live = scan(root, json_dir, doc["generic_threshold"], _self_rel(root, map_path))

    recorded_tabs, live_tabs = set(doc["tabs"]), set(live["tabs"])
    for tab in sorted(recorded_tabs - live_tabs):
        problems.append(f"{tab}: recorded in the map but not an exported tab")
    for tab in sorted(live_tabs - recorded_tabs):
        problems.append(f"{tab}: exported tab missing from the map")

    expected_machinery = sorted(set(MAP_MACHINERY) | {_self_rel(root, map_path)})
    if doc["map_machinery"] != expected_machinery:
        problems.append(
            f"map_machinery differs: recorded {doc['map_machinery']} vs {expected_machinery}")
    if doc["generic_files"] != live["generic_files"]:
        problems.append(
            "generic_files differ: recorded "
            f"{doc['generic_files']} vs scanned {live['generic_files']}")

    for tab in sorted(recorded_tabs & live_tabs):
        rec, got = doc["tabs"][tab], live["tabs"][tab]
        if not isinstance(rec, dict) or set(rec) < {"class", "machine", "prose"}:
            problems.append(f"{tab}: entry lacks class, machine or prose")
            continue
        for field in ("machine", "prose"):
            if rec[field] != got[field]:
                problems.append(
                    f"{tab}: {field} consumers differ: recorded {rec[field]} vs scanned {got[field]}")
        if rec["class"] != got["class"]:
            problems.append(
                f"{tab}: class recorded {rec['class']!r} but the scan derives {got['class']!r}")
        for rel in list(rec["machine"]) + list(rec["prose"]):
            if not os.path.isfile(os.path.join(root, rel)):
                problems.append(f"{tab}: recorded consumer {rel!r} does not exist")

    if doc["counts"] != live["counts"]:
        problems.append(f"counts differ: recorded {doc['counts']} vs scanned {live['counts']}")
    if not str(doc["does_not_establish"]).strip():
        problems.append("does_not_establish is empty")
    return problems


def _self_rel(root: str, map_path: str) -> str:
    """The map's path relative to the scan root, or '' when it lies outside."""
    rel = os.path.relpath(os.path.abspath(map_path), root)
    return "" if rel.startswith(os.pardir) else rel


def write_map(root: str, map_path: str, json_dir: str, threshold: int) -> dict:
    live = scan(root, json_dir, threshold, _self_rel(root, map_path))
    doc = {
        "schema": SCHEMA,
        "_comment": (
            "Which register tabs anything in this repository reads, quotes, or neither. "
            "Generated and re-verified by tools/consumers_check.py; every class is derived "
            "from the scan, never typed by hand. tools/registers_check.py checks every tab "
            "structurally without naming any of them, so a tab listed here as UNREAD is "
            "still imported and structurally checked — it is simply read by nothing."),
        "generic_threshold": threshold,
        "map_machinery": sorted(set(MAP_MACHINERY) | {_self_rel(root, map_path)}),
        "map_machinery_rule": (
            "Excluded from the corpus: the map, its checker and its controls name tabs only "
            "to describe or test the rule, never to read one."),
        "generic_rule": (
            "A file naming at least generic_threshold of the tabs is generic machinery "
            "(the importer, its export diff, its test, the register README's tab list). "
            "It touches every tab by construction and is excluded from per-tab attribution."),
        "machine_rule": (
            "A file under tools/, tests/, engine/, research/, claims/, or a non-export JSON "
            "file under registers/, whose bytes contain '<tab>.json' or the quoted token "
            "\"<tab>\" or '<tab>'."),
        "prose_rule": (
            "A Markdown file whose bytes contain '<tab>.json' or the backticked token `<tab>`. "
            "A bare word is not enough: 'definitions' and 'relations' are ordinary English."),
        "does_not_establish": (
            "Nothing here reads, checks or grades any register cell. A tab with many consumers "
            "is not more correct than one with none; an UNREAD tab is not defective, only "
            "unused here. No class is a status, a promotion, a review verdict or a licensing "
            "predicate, and no claim, premise or obligation moves because of this map. It "
            "measures this repository's coverage of the export, not the export's coverage of "
            "the Drive, and not the truth of anything either states."),
        "generic_files": live["generic_files"],
        "counts": live["counts"],
        "tabs": live["tabs"],
    }
    with open(map_path, "w", encoding="utf-8") as handle:
        json.dump(doc, handle, ensure_ascii=False, indent=1)
        handle.write("\n")
    return doc


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=REPO, help="repository root to scan")
    parser.add_argument("--map", default=None, help="path to CONSUMERS.json")
    parser.add_argument("--json-dir", default=None, help="directory of <tab>.json exports")
    parser.add_argument("--threshold", type=int, default=30,
                        help="tabs named before a file counts as generic machinery (--write only)")
    parser.add_argument("--write", action="store_true", help="regenerate the map from the scan")
    args = parser.parse_args(argv)

    root = os.path.abspath(args.root)
    map_path = args.map or os.path.join(root, MAP_REL)
    json_dir = args.json_dir or os.path.join(root, JSON_REL)

    if args.write:
        doc = write_map(root, map_path, json_dir, args.threshold)
        counts = doc["counts"]
        print(f"wrote {os.path.relpath(map_path, root)}: " + " ".join(
            f"{k}={v}" for k, v in counts.items()))
        return 0

    try:
        problems = check(root, map_path, json_dir)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"consumers_check: {exc}")
        print("A pass here is a coverage fact about this repository. It reads no cell, "
              "verifies no mathematics and moves no status.")
        return 1
    for problem in problems:
        print("NEW    " + problem)
    doc = load_map(map_path)
    counts = doc["counts"]
    print("consumers_check: " + " ".join(f"{k}={v}" for k, v in counts.items())
          + f" problems={len(problems)}")
    print("A pass here is a coverage fact about this repository. It reads no cell, "
          "verifies no mathematics and moves no status.")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
