#!/usr/bin/env python3
"""The mirror index is derived from the manifests, never typed.

``drive/README.md`` used to describe the mirror set in a prose sentence
beginning "Mirrored so far:".  Every port made it staler; by 2026-09-20 it named
six lanes and the tree held twenty-one.  Three separate lane verifications found
the same shape inside the lane READMEs -- a header reading "one object so far"
above twenty-six objects, a coverage table still reading "0 -- not ported by
this lane" for folders the same commit had filled.  None of them inflated a
research claim; all of them told a reader something false about the tree.

So the index is generated.  ``drive/MIRRORS.md`` is written by this tool from
the manifests themselves, and this tool recomputes it on every run and refuses
any drift.  A port that adds a lane, a file or a tree-only row and does not
regenerate the index turns CI red, by name.

Per lane it counts, from every ``_MANIFEST.jsonl`` under that lane:

``manifests``   directories holding files, one manifest each
``stored``      rows with ``stored: true`` -- bytes this repository holds
``exact``       stored rows with ``exact: true`` -- the row's digest is the one
                the 2026-09-17 inventory declares for that Drive id.  An
                ``exact: false`` row is a text export of a native Google Doc,
                for which no payload digest exists anywhere in the corpus: a
                reading copy, not the object.
``tree-only``   rows with ``stored: false`` -- the lane indexes the item and
                does not hold its bytes
``bytes``       the sum of the stored rows' byte counts

What this does NOT establish: these are counts of rows and bytes.  Nothing here
verifies a digest -- ``tools/verify_manifests.py`` does that -- and nothing here
reads, grades or moves any claim, premise or obligation.  A large lane is not a
more authoritative lane, an ``exact`` count is a count of matching digests and
not of correct mathematics, and a mirror is a copy: not review, not replay, not
endorsement, not promotion.

Run:  python3 tools/mirrors_index_check.py            # recompute and compare
      python3 tools/mirrors_index_check.py --write    # regenerate the index
Every path is resolved when ``main()`` runs, never at import time.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIRRORS_REL = os.path.join("drive", "mirrors")
DELTAS_REL = os.path.join("drive", "deltas")
INVENTORY_REL = os.path.join("drive", "inventory.jsonl")
INDEX_REL = os.path.join("drive", "MIRRORS.md")

HEADER = "| lane | manifests | stored | exact | tree-only | bytes |"
RULE = "|---|---:|---:|---:|---:|---:|"
COV_HEADER = "| Drive lane | inventory items | held | indexed | neither |"
COV_RULE = "|---|---:|---:|---:|---:|"

PREAMBLE = """<!-- Generated by tools/mirrors_index_check.py. Do not edit by hand:
     the checker recomputes every number from the manifests and refuses drift. -->

# What `drive/mirrors/` holds

Byte-exact copies of selected Drive objects, laid out as
`mirrors/<Drive lane folder>/<path inside the lane>/`, one `_MANIFEST.jsonl` per
directory that holds files. Every digest and byte count in those manifests is
verified by [`tools/verify_manifests.py`](../tools/verify_manifests.py) in CI;
every quotation in the lane READMEs is verified by
[`tools/mirror_quotes_check.py`](../tools/mirror_quotes_check.py); this table is
generated from the manifests by
[`tools/mirrors_index_check.py`](../tools/mirrors_index_check.py).

A row with **`exact: true`** hashes to the digest the 2026-09-17 inventory
declares for that Drive id. A row with **`exact: false`** is a text export of a
native Google Doc, for which no payload digest exists anywhere in the corpus: a
reading copy, not the object. A **tree-only** row indexes an item the lane does
not hold the bytes of.

**A mirror is a copy. It is not review, replay, endorsement or promotion, and it
moves no status.** Nothing under `02_LEGACY_Q0_ARCHIVE`, `03_PERSONAL_AND_EARLIER_RESEARCH`,
`90_QUARANTINE_AND_TRIAGE` or the vault may be cited as evidence.
"""

COVERAGE_PREAMBLE = """
## How much of the Drive is here

Derived by reading the `drive_path` of every manifest row under `drive/mirrors/`
and `drive/deltas/` and matching its Drive id against `drive/inventory.jsonl`.
Lanes are the top-level Drive folders, split one level further inside
`01_ACTIVE_RESEARCH_PACKAGES`, and the split is read off the paths themselves --
no lane list is typed anywhere.

**held** — the bytes are in this repository and the id has an inventory row.
**indexed** — a manifest carries a tree-only row for the id and not its bytes.
**neither** — the inventory knows the item and no manifest mentions it.

An object created after the 2026-09-17 snapshot has no inventory row, so it is
stored and counted in the lane table above while contributing nothing to any
column here. That is why the two tables' totals differ.
"""

TRAILER = """
Counts are of manifest rows and stored bytes. They say nothing about whether any
mirrored document is correct, current or authoritative; each lane's README
quotes the source's own status banners, and those banners are the source's
claims, not this repository's.
"""


def lane_counts(mirrors_dir, lane):
    """Count one lane's manifest rows."""
    manifests = stored = exact = tree_only = total_bytes = 0
    for dirpath, _dirs, files in os.walk(os.path.join(mirrors_dir, lane)):
        if "_MANIFEST.jsonl" not in files:
            continue
        manifests += 1
        with open(os.path.join(dirpath, "_MANIFEST.jsonl"), encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                row = json.loads(line)
                if row.get("stored"):
                    stored += 1
                    total_bytes += row.get("bytes") or 0
                    if row.get("exact") is True:
                        exact += 1
                else:
                    tree_only += 1
    return {"manifests": manifests, "stored": stored, "exact": exact,
            "tree_only": tree_only, "bytes": total_bytes}


def exactness_claims(root, mirrors_rel, deltas_rel, inventory_rel):
    """What every ``exact: true`` row is actually claiming.

    The field means two different things in the two roots, and until 2026-09-20
    nothing said so.

    Under ``drive/mirrors/`` it means the stored bytes hash to the digest the
    2026-09-17 inventory declares for that Drive id.  That is checkable, so it is
    checked here and a row that claims it without an inventory row, without a
    declared digest, or against a different digest is a problem.

    Under ``drive/deltas/`` it cannot mean that: a delta object was created after
    the snapshot the inventory is of, so no corpus digest for it exists anywhere.
    There it means the row holds the raw bytes rather than a text export of a
    native Google Doc.  Those rows are counted and reported, never failed -- but
    the count is printed so nobody reads one of them as agreement with a corpus
    value that does not exist.
    """
    inventory = {}
    path = os.path.join(root, inventory_rel)
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as handle:
            for line in handle:
                try:
                    record = json.loads(line)
                except ValueError:
                    continue
                if isinstance(record, dict) and record.get("id"):
                    inventory[record["id"]] = record

    backed = post_snapshot = 0
    problems = []
    for rel, enforced in ((mirrors_rel, True), (deltas_rel, False)):
        base = os.path.join(root, rel)
        if not os.path.isdir(base):
            continue
        for dirpath, _dirs, files in os.walk(base):
            if "_MANIFEST.jsonl" not in files:
                continue
            manifest = os.path.join(dirpath, "_MANIFEST.jsonl")
            with open(manifest, encoding="utf-8") as handle:
                for number, line in enumerate(handle, 1):
                    line = line.strip()
                    if not line:
                        continue
                    row = json.loads(line)
                    if row.get("exact") is not True:
                        continue
                    where = f"{os.path.relpath(manifest, root)}:{number}"
                    source = inventory.get(row.get("id"))
                    if source is None or not source.get("sha256"):
                        if enforced:
                            problems.append(
                                (where, row.get("id"),
                                 "claims exact: true, and the inventory declares no digest "
                                 "for that id to be exact against"))
                        else:
                            post_snapshot += 1
                        continue
                    if source["sha256"] != row.get("sha256"):
                        problems.append(
                            (where, row.get("id"),
                             f"claims exact: true but its digest {str(row.get('sha256'))[:12]}… "
                             f"is not the inventory's {source['sha256'][:12]}…"))
                        continue
                    backed += 1
    return backed, post_snapshot, problems


def repeated_ids(root, rels):
    """Drive ids carried by more than one row of the same manifest.

    One exists on purpose: a lane recorded an object tree-only under an earlier
    store-size limit, and a later port added a stored row beside it rather than
    rewriting the first, because this repository does not edit a record in place.
    Both rows are true of their moment and the later one says so in its note.  A
    consumer keying by id would silently pick one, so the count is printed: a
    second, unexplained case shows up instead of hiding.
    """
    found = []
    for rel in rels:
        base = os.path.join(root, rel)
        if not os.path.isdir(base):
            continue
        for dirpath, _dirs, files in os.walk(base):
            if "_MANIFEST.jsonl" not in files:
                continue
            path = os.path.join(dirpath, "_MANIFEST.jsonl")
            seen = {}
            with open(path, encoding="utf-8") as handle:
                for line in handle:
                    line = line.strip()
                    if not line:
                        continue
                    row = json.loads(line)
                    key = row.get("id")
                    if not key:
                        continue
                    seen[key] = seen.get(key, 0) + 1
            for key, count in sorted(seen.items()):
                if count > 1:
                    found.append((os.path.relpath(path, root), key, count))
    return found


def survey(root, mirrors_rel):
    mirrors_dir = os.path.join(root, mirrors_rel)
    lanes = sorted(name for name in os.listdir(mirrors_dir)
                   if os.path.isdir(os.path.join(mirrors_dir, name)))
    return [(lane, lane_counts(mirrors_dir, lane)) for lane in lanes]


def drive_lane(path):
    """The lane a Drive path belongs to, read off the path and never typed."""
    parts = [p for p in (path or "").split("/") if p]
    if not parts:
        return None
    if parts[0] == "01_ACTIVE_RESEARCH_PACKAGES" and len(parts) >= 2:
        return "/".join(parts[:2])
    return parts[0]


def manifest_rows(root, rels):
    for rel in rels:
        base = os.path.join(root, rel)
        for dirpath, _dirs, files in os.walk(base):
            if "_MANIFEST.jsonl" not in files:
                continue
            with open(os.path.join(dirpath, "_MANIFEST.jsonl"), encoding="utf-8") as handle:
                for line in handle:
                    line = line.strip()
                    if line:
                        yield json.loads(line)


def coverage(root, mirrors_rel, deltas_rel, inventory_rel):
    """Per Drive lane: inventory items, and how many this repository holds."""
    lanes, ids = {}, {}
    inventory = os.path.join(root, inventory_rel)
    if not os.path.isfile(inventory):
        return []
    with open(inventory, encoding="utf-8") as handle:
        for line in handle:
            try:
                record = json.loads(line)
            except ValueError:
                continue
            lane = drive_lane(record.get("path") or record.get("drive_path"))
            if lane is None:
                continue
            lanes[lane] = lanes.get(lane, 0) + 1
            if record.get("id"):
                ids.setdefault(lane, set()).add(record["id"])

    held, indexed = {}, {}
    rels = [r for r in (mirrors_rel, deltas_rel) if os.path.isdir(os.path.join(root, r))]
    for row in manifest_rows(root, rels):
        lane = drive_lane(row.get("drive_path"))
        if lane is None or not row.get("id"):
            continue
        bucket = held if row.get("stored") else indexed
        bucket.setdefault(lane, set()).add(row["id"])

    out = []
    for lane in sorted(lanes, key=lambda k: (-lanes[k], k)):
        known = ids.get(lane, set())
        h = held.get(lane, set()) & known
        i = (indexed.get(lane, set()) - held.get(lane, set())) & known
        out.append((lane, {"items": lanes[lane], "held": len(h), "indexed": len(i),
                           "neither": lanes[lane] - len(h) - len(i)}))
    return out


def render_coverage(rows):
    lines = [COVERAGE_PREAMBLE, COV_HEADER, COV_RULE]
    totals = {"items": 0, "held": 0, "indexed": 0, "neither": 0}
    for lane, counts in rows:
        for key in totals:
            totals[key] += counts[key]
        lines.append(f"| `{lane}` | {counts['items']} | {counts['held']} | "
                     f"{counts['indexed']} | {counts['neither']} |")
    lines.append(f"| **{len(rows)} Drive lanes** | **{totals['items']}** | **{totals['held']}** | "
                 f"**{totals['indexed']}** | **{totals['neither']}** |")
    return "\n".join(lines)


def render(rows, coverage_rows=None):
    lines = [PREAMBLE, HEADER, RULE]
    totals = {"manifests": 0, "stored": 0, "exact": 0, "tree_only": 0, "bytes": 0}
    for lane, counts in rows:
        for key in totals:
            totals[key] += counts[key]
        lines.append(
            f"| `{lane}` | {counts['manifests']} | {counts['stored']} | "
            f"{counts['exact']} | {counts['tree_only']} | {counts['bytes']:,} |")
    lines.append(
        f"| **{len(rows)} lanes** | **{totals['manifests']}** | **{totals['stored']}** | "
        f"**{totals['exact']}** | **{totals['tree_only']}** | **{totals['bytes']:,}** |")
    if coverage_rows is not None:
        lines.append(render_coverage(coverage_rows))
    lines.append(TRAILER)
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=REPO)
    parser.add_argument("--mirrors", default=MIRRORS_REL)
    parser.add_argument("--deltas", default=DELTAS_REL)
    parser.add_argument("--inventory", default=INVENTORY_REL)
    parser.add_argument("--index", default=INDEX_REL)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)

    root = os.path.abspath(args.root)
    mirrors_dir = os.path.join(root, args.mirrors)
    index_path = os.path.join(root, args.index)

    if not os.path.isdir(mirrors_dir):
        print(f"mirrors_index_check: no mirror directory at {args.mirrors}")
        return 1

    rows = survey(root, args.mirrors)
    cover = coverage(root, args.mirrors, args.deltas, args.inventory)
    repeats = repeated_ids(root, (args.mirrors, args.deltas))
    backed, post_snapshot, exact_problems = exactness_claims(
        root, args.mirrors, args.deltas, args.inventory)
    want = render(rows, cover)

    if args.write:
        with open(index_path, "w", encoding="utf-8") as handle:
            handle.write(want)
        print(f"mirrors_index_check: wrote {args.index} lanes={len(rows)}")
        return 0

    if not os.path.isfile(index_path):
        print(f"mirrors_index_check: {args.index} is missing; run --write")
        return 1

    with open(index_path, encoding="utf-8") as handle:
        have = handle.read()

    problems = 0
    if have != want:
        have_rows = [l for l in have.splitlines() if l.startswith("| `") or l.startswith("| **")]
        want_rows = [l for l in want.splitlines() if l.startswith("| `") or l.startswith("| **")]
        for line in want_rows:
            if line not in have_rows:
                print(f"mirrors_index_check: the tree says {line.strip()} and the index does not")
                problems += 1
        for line in have_rows:
            if line not in want_rows:
                print(f"mirrors_index_check: the index says {line.strip()} and the tree does not")
                problems += 1
        if problems == 0:
            print("mirrors_index_check: the index's prose differs from the generator's; "
                  "regenerate it with --write rather than editing it")
            problems = 1

    for where, key, why in exact_problems:
        print(f"mirrors_index_check: {where}: Drive id {key} {why}")
        problems += 1

    for rel, key, count in repeats:
        print(f"mirrors_index_check: {rel}: Drive id {key} is carried by {count} rows "
              "of this manifest; the later row's note must say why")

    lanes = len(rows)
    stored = sum(c["stored"] for _lane, c in rows)
    items = sum(c["items"] for _lane, c in cover)
    held = sum(c["held"] for _lane, c in cover)
    print(f"mirrors_index_check: lanes={lanes} stored={stored} "
          f"inventory={items} held={held} exact_backed_by_inventory={backed} "
          f"exact_post_snapshot={post_snapshot} repeated_ids={len(repeats)} "
          f"problems={problems}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
